"""ASCII logos for larpfetch.

Logos adapted from fastfetch (MIT licensed).
Each logo is a list of strings (lines).
"""

from __future__ import annotations

from typing import Dict, List

LOGOS: Dict[str, List[str]] = {
    "generic": [
        "         _       _      __       _        ",
        "  _   __(_)___  (_)____/ /___  (_)___ _ _ ",
        " | | / / / __ \\/ / ___/ / __ \\/ / __ `(_)",
        " | |/ / / / / / / /__/ / / / / / / / / /  ",
        " |___/_/_/ /_/_/\\___/_/_/ /_/_/_/ /_/_/   ",
    ],
    "arch": [
        "                  -`",
        "                 .o+`",
        "                `ooo/",
        "               `+oooo:",
        "              `+oooooo:",
        "              -+oooooo+:",
        "            `/:-:++oooo+:",
        "           `/++++/+++++++:",
        "          `/++++++++++++++:",
        "         `/+++ooooooooooooo/`",
        "        ./+ooooooooosssso++/`",
        "       .+osssssssso++osssssso+`",
        "      -osssssso.      :ssssssso.",
        "     :osssssss/        osssso+++.",
        "    /ossssssss/        +ssssooo/-",
        "  `/ossssso+/:-        -:/+osssso+-",
        " `+sso+:-`                 `.-/+oso:",
        "`++:.                           `-/+/",
        ".`                                 `/",
    ],
    "arch_small": [
        "      /\\",
        "     /  \\",
        "    /    \\",
        "   /      \\",
        "  /   ,,   \\",
        " /   |  |   \\",
        "/_-''    ''-_\\",
    ],
    "ubuntu": [
        "                             ....",
        "              .',:clooo:  .:looooo:.",
        "           .;looooooooc  .oooooooooo'",
        "        .;looooool:,''.  :ooooooooooc",
        "       ;looool;.         'oooooooooo,",
        "      ;clool'             .cooooooc.  ,,",
        "         ...                ......  .:oo,",
        "  .;clol:,.                        .loooo'",
        " :ooooooooo,                        'ooool",
        "'ooooooooooo.                        loooo.",
        "'ooooooooool                         coooo.",
        " ,loooooooc.                        .loooo.",
        "   .,;;;'.                          ;ooooc",
        "       ...                         ,ooool.",
        "    .coooc.              ..',,'.  .cooo.",
        "      ;ooooo:.           ;oooooooc.  :l.",
        "       .coooooc,..      coooooooooo.",
        "         .:ooooooolc:. .ooooooooooo'",
        "           .':looooo;  ,oooooooooc",
        "               ..';::c'  .;loooo:'",
    ],
    "debian": [
        "        _,met$$$$$$$$$$gg.",
        "     ,g$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$P.",
        "   ,g$$$$P\"\"\"       \"\"\"Y$$$.\".",
        "  ,$$$$P'              `$$$$$$.",
        "',$$$$P       ,ggs.     `$$$$b:",
        "`d$$$$'     ,$P\"`    .    $$$$$$",
        " $$$$P      d$'      ,    $$$$P",
        " $$$$:      $$$.   -    ,d$$$$'",
        " $$$$;      Y$b._   _,d$P'",
        " Y$$$$.    .`\"`\"Y$$$$$$$$P\"",
        " `$$b      \"-.__",
        "  `Y$$$b",
        "   `Y$$$$.",
        "     `$$$$b.",
        "       `Y$$$$b.",
        "         `\"Y$$b._",
        "             `\"\"\"",
    ],
    "fedora": [
        "             .',;::::;,.",
        "         .';:cccccccccccc:;,.",
        "      .;cccccccccccccccccccccc;.",
        "    .:cccccccccccccccccccccccccc:.",
        "  .;ccccccccccccc;.:dddl:.;ccccccc;.",
        " .:ccccccccccccc;OWMKOOXMWd;ccccccc:.",
        ":ccccccccccccc;KMMc;cc;xMMc;ccccccc:,",
        ",cccccccccccccc;MMM.;cc;.;WW;cccccccc,",
        ":cccccccccccccc;MMM.;cccccccccccccccc:",
        ":ccccccc;oxOOOo;MMM000k.;cccccccccccc:",
        "cccccc;0MMKxdd:;MMMkddc.;cccccccccccc;",
        "ccccc;XMO';cccc;MMM.;cccccccccccccccc'",
        "ccccc;MMo;ccccc;MMW.;ccccccccccccccc;",
        "ccccc;0MNc.;ccc.xMMd;ccccccccccccccc;",
        "cccccc;dNMWXXXWM0:;cccccccccccccc:,",
        "cccccccc;.:odl:.;cccccccccccccc:,.",
        "ccccccccccccccccccccccccccccc:'.",
        ":ccccccccccccccccccccccc:;,..",
        " ':cccccccccccccccc::;,.",
    ],
    "windows": [
        "        ,.=:!!t3Z3z.,",
        "       :tt:::tt333EE3",
        "       Et:::ztt333EEEL @Ee.,      ..,",
        "      ;tt:::tt333EE7 ;EEEEEEttttt33#",
        "     :Et:::zt333EEQ. $EEEEEttttt33QL",
        "     it::::tt333EEF @EEEEEEttttt33F",
        "    ;3=*^``\"*4EEV :EEEEEEttttt33@.",
        "    ,.=::::!t=., `  @EEEEEEtttz33QF",
        "   ;::::::::zt33)   \"4EEEtttji3P*",
        "  :t::::::::tt33.:Z3z..  ``  ,..g.",
        "  i::::::::zt33F AEEEtttt::::ztF",
        " ;:::::::::t33V ;EEEttttt::::t3",
        " E::::::::zt33L @EEEtttt::::z3F",
        "{3=*^``*4E3) ;EEEtttt:::::tZ`",
        "             `  :EEEEtttt::::z7",
        "                 \"VEzjt:;;z>*`",
    ],
    "macos": [
        "                     ..'",
        "                 ,xNMM.",
        "               .OMMMMo",
        "               lMM\"",
        "     .;loddo:.  .olloddol;.",
        "   cKMMMMMMMMMMNWMMMMMMMMMM0:",
        " .KMMMMMMMMMMMMMMMMMMMMMMMWd.",
        " XMMMMMMMMMMMMMMMMMMMMMMMX.",
        ";MMMMMMMMMMMMMMMMMMMMMMMM:",
        ":MMMMMMMMMMMMMMMMMMMMMMMM:",
        ".MMMMMMMMMMMMMMMMMMMMMMMX.",
        " kMMMMMMMMMMMMMMMMMMMMMMMMWd.",
        " 'XMMMMMMMMMMMMMMMMMMMMMMMMMMk",
        "  'XMMMMMMMMMMMMMMMMMMMMMMMMK.",
        "    kMMMMMMMMMMMMMMMMMMMMMMd",
        "     ;KMMMMMMMWXXWMMMMMMMk.",
        "       \"cooc*\"    \"*coo'",
    ],
    "alpine": [
        "                 ..",
        "               .PLTJ.",
        "              <><><><>",
        "     KKSSV' 4KKK LJ  KKKL.'VSSKK",
        "     KKV' 4KKKKK LJ  KKKKAL 'VKK",
        "     V' ' 'VKKKK LJ  KKKKV' ' 'V",
        "     .4MA.' 'VKK LJ  KKV' '.4Mb.",
        "   . KKKKKA.' 'V LJ  V' '.4KKKKK .",
        "  .4D KKKKKKKKA.'' LJ  ''.4KKKKKKK FA.",
        " <QDD ++++++++++++  +++++++++++++ GFD>",
        " '$VD KKKKKKKK'.. LJ  ..'KKKKKKKK FV",
        "   ' VKKKKK'. .4 LJ  K. .'KKKKKV '",
        "      'VK'. .4KK LJ  KKA. .'KV'",
        "     A. . .4KKKK LJ  KKKKA. . .4",
        "     KKA. 'KKKKK LJ  KKKKK' .4KK",
        "     KKSSA. VKKK LJ  KKKV .4SSKK",
        "              <><><><>",
        "               'MKKM'",
        "                 ''",
    ],
    "centos": [
        "        ,.=:!!t3Z3z.,",
        "       :tt:::tt333EE3",
        "       Et:::ztt333EEEL @Ee.,      ..,",
        "      ;tt:::tt333EE7 ;EEEEEEttttt33#",
        "     :Et:::zt333EEQ. $EEEEEttttt33QL",
        "     it::::tt333EEF @EEEEEEttttt33F",
        "    ;3=*^``\"*4EEV :EEEEEEttttt33@.",
        "    ,.=::::!t=., `  @EEEEEEtttz33QF",
        "   ;::::::::zt33)   \"4EEEtttji3P*",
        "  :t::::::::tt33.:Z3z..  ``  ,..g.",
        "  i::::::::zt33F AEEEtttt::::ztF",
        " ;:::::::::t33V ;EEEttttt::::t3",
        " E::::::::zt33L @EEEtttt::::z3F",
        "{3=*^``*4E3) ;EEEtttt:::::tZ`",
        "             `  :EEEEtttt::::z7",
        "                 \"VEzjt:;;z>*`",
    ],
    "parrot": [
        "  `:oho/-`",
        "`mMMMMMMMMMMMNmmdhy-",
        " dMMMMMMMMMMMMMMMMMMs`",
        " +MMsohNMMMMMMMMMMMMMm/",
        " .My   .+dMMMMMMMMMMMMMh.",
        "  +       :NMMMMMMMMMMMMNo",
        "           `yMMMMMMMMMMMMMm:",
        "             /NMMMMMMMMMMMMMy`",
        "              .hMMMMMMMMMMMMMN+",
        "                  ``-NMMMMMMMMMd-",
        "                     /MMMMMMMMMMMs`",
        "                      mMMMMMMMsyNMN/",
        "                      +MMMMMMMo  :sNh.",
        "                      `NMMMMMMm     -o/",
        "                       oMMMMMMM.",
        "                       `NMMMMMM+",
        "                        +MMd/NMh",
        "                         mMm -mN`",
        "                         /MM  `h:",
        "                          dM`   .",
        "                          :M-",
        "                           d:",
        "                           -+",
        "                            -",
    ],
    "nixos": [
        "          ▗▄▄▄       ▗▄▄▄▄    ▄▄▄▖",
        "          ▜███▙       ▜███▙  ▟███▛",
        "           ▜███▙       ▜███▙▟███▛",
        "            ▜███▙       ▜██████▛",
        "     ▟█████████████████▙ ▜████▛     ▟▙",
        "    ▟███████████████████▙ ▜███▙    ▟██▙",
        "           ▄▄▄▄▖           ▜███▙  ▟███▛",
        "          ▟███▛             ▜██▛ ▟███▛",
        "         ▟███▛               ▜▛ ▟███▛",
        " ▟███████████▛                  ▟██████████▙",
        " ▜██████████▛                  ▟███████████▛",
        "      ▟███▛ ▟▙               ▟███▛",
        "     ▟███▛ ▟██▙             ▟███▛",
        "    ▟███▛  ▜███▙           ▝▀▀▀▀",
        "    ▜██▛    ▜███▙ ▜██████████████████▛",
        "     ▜▛     ▟████▙ ▜████████████████▛",
        "           ▟██████▙         ▜███▙",
        "          ▟███▛▜███▙         ▜███▙",
        "         ▟███▛  ▜███▙         ▜███▙",
        "         ▝▀▀▀    ▀▀▀▀▘         ▀▀▀▘",
    ],
    "kali": [
        "..............",
        "            ..,;:ccc,.",
        "          ......''';lxO.",
        "...''''..........,:ld;",
        "           .';;;:::;,,.x,",
        "      ..'''.            0Xxoc:,.  ...",
        "  ....                ,ONkc;,;cokOdc',.",
        " .                   OMo           ':ddo.",
        "                    dMc               :OO;",
        "                    0M.                 .:o.",
        "                    ;Wd",
        "                     ;XO,",
        "                       ,d0Odlc;,..",
        "                           ..',;:cdOOd::,.",
        "                                    .:d;'.:;.",
        "                                       'd,  .'",
        "                                         ;l   ..",
        "                                          .o",
        "                                            c",
        "                                            .'",
        "                                             .",
    ],
    "gentoo": [
        "         -/oyddmdhs+:.",
        "     -odNMMMMMMMMNNmhy+$-",
        "   -yNMMMMMMMMMMMNNNmmdhy+-",
        " `omMMMMMMMMMMMMNmdmmmmddhhy+/",
        " omMMMMMMMMMMMNhhyyyo/hmdddhhhd+o`",
        ".ydMMMMMMMMMMdhs++so/s/mdddhhhhdm+`",
        " oyhdmNMMMMMMMNdyooy/dmddddhhhhyhNd.",
        "  :oyhdNNMMMMMMMNNNmmdddhhhhhyymMh",
        "    .+sydNMMMMMNNNmmmdddhhhhhhmMmy",
        "       /mMMMMMMNNNmmmdddhhhhhmNhs:",
        "    `oNMMMMMMMNNNmmmddddhhdmNhs+`",
        "  `sNMMMMMMMMNNNmmmdddddmNMhs/.",
        " /NMMMMMMMMNNNNmmmdddmNMNdso:",
        "+MMMMMMMNNNNNmmmmdmNMNdso/-",
        "yMMNNNNNNNmmmmmNNMmhs+/$-",
        "/hMMNNNNNNNNMNdhs++/$-",
        "`/ohdmmddhys+++/:`.",
        "  `-//////:--.",
    ],
    "opensuse": [
        "           .;ldkO0000Okdl;.",
        "       .;d00xl:^''''''^:ok00d;.",
        "     .d00l'                'o00d.",
        "   .d0Kd'  Okxol:;,.          :O0d",
        "  .OKKKK0kOKKKKKKKKKKOxo:,      lKO.",
        " ,0KKKKKKKKKKKKKKKK0P^,,,^dx:    ;00,",
        ".OKKKKKKKKKKKKKKKKk'.oOPPb.'0k.   cKO.",
        ":KKKKKKKKKKKKKKKK: kKx..dd lKd   'OK:",
        "dKKKKKKKKKKOx0KKKd ^0KKKO' kKKc   dKd",
        "dKKKKKKKKKK;.;oOKx,..^..;kKKK0.  dKd",
        ":KKKKKKKKKK0o;...^cdxxOK0O/^^'  .0K:",
        " kKKKKKKKKKKKKK0x;,,......,;od  lKk",
        " '0KKKKKKKKKKKKKKKKKKKK00KKOo^  c00'",
        "  'kKKKKOxddxkOO00000Okxoc;''   .dKk'",
        "    l0Ko.                    .c00l'",
        "     'l0Kk:.              .;xK0l'",
        "        'lkK0xl:;,,,,;:ldO0kl'",
        "            '^:ldxkkkkxdl:^'",
    ],
    "manjaro": [
        "        -o          o-",
        "          +hydNNNNdyh+",
        "        +mMMMMMMMMMMMMm+",
        "      `dMMm:NMMMMMMN:mMMd`",
        "      hMMMMMMMMMMMMMMMMMMh",
        "  ..  yyyyyyyyyyyyyyyyyyyy  ..",
        ".mMMm`MMMMMMMMMMMMMMMMMMMM`mMMm.",
        ":MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM:",
        ":MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM:",
        ":MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM:",
        ":MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM:",
        "-MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM-",
        " +yy+ MMMMMMMMMMMMMMMMMMMM +yy+",
        "      mMMMMMMMMMMMMMMMMMMm",
        "      `/++MMMMh++hMMMM++/`",
        "          MMMMo  oMMMM",
        "          MMMMo  oMMMM",
        "          oNMm-  -mMNs",
    ],
    "haiku": [
        "           MMMM              MMMM",
        "           MMMM              MMMM",
        "           MMMM              MMMM",
        "           MMMM              MMMM",
        "           MMMM       .ciO| /YMMMMM*\"",
        "           MMMM   .cOMMMMM|/MMMMM/`",
        " ,         ,iMM|/MMMMMMMMMMMMMMM*",
        "  `*.__,-cMMMMMMMMMMMMMMMMM/`.MMM",
        "           MMMMMMMMM/`:MMM/  MMMM",
        "           MMMM              MMMM",
        "           MMMM              MMMM",
        "           \"\"\"\"              \"\"\"\"",
    ],
    "templeos": [
        "                  ___  ___  ",
        "                 /  / /  /  ",
        "                /  / /  /   ",
        "    ____       /  / /  /    ",
        "   /    \\    /  / /  /     ",
        "  /  O O \\ /  / /  /      ",
        "  \\  ___  /  / /  /       ",
        "   |     | /  / /  /      ",
        "   |     |/  / /  /       ",
        "   |     /  / /  /        ",
        "   |     /  / /  /        ",
        "   |____/  / /  /         ",
    ],
    "nasa": [
        "     _   ___  ____  ",
        "    | \\ |   \\|  _ \\ ",
        "   |  \\| |) | | | |",
        "   |  \\  _ <| |_| |",
        "   |_|\\___\\_|____/ ",
    ],
    "windows95": [
        "         _  __",
        "        | |/ /",
        "   __ _ _|   / ___  _ __   ___",
        "  / _` | | \\ / _ \\| '_ \\ / _ \\",
        " | (_| | |  | (_) | | | |  __/",
        " \\__,_|_|_/ \\___/|_| |_|\\___|",
        "         |_|",
    ],
    "unknown": [
        "         .---.        ",
        "       /     \\       ",
        "      /.      \\      ",
        "     / . ;      \\     ",
        "    /   .        \\    ",
        "   /  .    .      \\   ",
        "  /  .   .   .    .\\  ",
        " /  .  .   .  .   . \\ ",
        "/:.  .   .  .  .   . :\\",
        "|:  .   .  .   .  .  :|",
        "|:.  .  .   .  .   . :|",
        "\\:.  .   .  .  .   .:/ ",
        " \\  .  .   .  .   /  ",
        "  \\   .   .  .   /   ",
        "   \\   .  .  .  /    ",
        "    \\  .   .  /     ",
        "     \\  .  . /      ",
        "      \\   . /       ",
        "       \\  .|        ",
        "        \\:./        ",
    ],

}


def _normalize(name: str) -> str:
    """Normalize an OS/distro/profile name for logo lookup."""
    name = name.lower().strip()
    if name in LOGOS:
        return name
    # Substring matching
    mappings = [
        ("arch", "arch"),
        ("ubuntu", "ubuntu"),
        ("debian", "debian"),
        ("fedora", "fedora"),
        ("windows", "windows"),
        ("mac", "macos"),
        ("darwin", "macos"),
        ("alpine", "alpine"),
        ("centos", "centos"),
        ("parrot", "parrot"),
        ("nixos", "nixos"),
        ("kali", "kali"),
        ("gentoo", "gentoo"),
        ("opensuse", "opensuse"),
        ("manjaro", "manjaro"),
        ("raspbian", "raspbian"),
        ("templeos", "templeos"),
        ("nasa", "nasa"),
        ("haiku", "haiku"),
    ]
    for pattern, logo_key in mappings:
        if pattern in name:
            return logo_key
    return "generic"


def select_logo(displayed_os: str) -> List[str]:
    """Select the appropriate logo based on the displayed OS/distro string."""
    key = _normalize(displayed_os)
    return LOGOS.get(key, LOGOS["generic"])


def get_logo_height(logo: List[str]) -> int:
    return len(logo)


def get_logo_width(logo: List[str]) -> int:
    return max(len(line) for line in logo) if logo else 0
