"""Built-in profiles that ship with larpfetch."""

from __future__ import annotations

from typing import Any

BUILTIN_PROFILES: dict[str, dict[str, Any]] = {
    "nasa": {
        "os": "NASA Linux",
        "hostname": "mainframe-01",
        "kernel": "5.15.0-nasa-security",
        "architecture": "x86_64",
        "cpu": "Quantum Potato 9000",
        "gpu": "Classified",
        "memory": "69 PiB",
        "shell": "nasa-sh",
        "terminal": "nasa-sh",
        "de": "Mission Control Desktop",
        "wm": "Mission Control WM",
        "compositor": "Mission Control WM",
        "resolution": "3840x2160",
        "package_count": "0 (custom repos)",
        "logo": "nasa",
    },
    "abomination": {
        "os": "Windows 11 Pro",
        "kernel": "6.18.7-arch1-1",
        "architecture": "arm64",
        "cpu": "Apple M7 Ultra",
        "gpu": "NVIDIA RTX 9090 Ti",
        "memory": "69 PiB",
        "shell": "HolyC",
        "terminal": "HolyC",
        "de": "GNOME 83",
        "wm": "GNOME Shell",
        "compositor": "Mutter",
        "resolution": "9999x9999 @ 500Hz",
        "package_count": "infinite",
        "package_manager": "apt btw",
    },
    "hacker": {
        "os": "Parrot OS",
        "distro": "Parrot Security OS 6.3",
        "kernel": "6.9.1-parrot1-amd64",
        "architecture": "x86_64",
        "cpu": "Intel Core i9-14900K",
        "gpu": "NVIDIA RTX 4090",
        "memory": "128 GiB",
        "shell": "zsh",
        "terminal": "kitty",
        "de": "KDE Plasma 6",
        "wm": "KWin",
        "compositor": "KWin",
        "resolution": "2560x1440 @ 165Hz",
        "package_count": "4200",
        "package_manager": "apt",
        "logo": "parrot",
    },
    "macbook": {
        "os": "macOS 15.0 Sequoia",
        "distro": "macOS 15.0",
        "kernel": "Darwin 24.0.0",
        "architecture": "arm64",
        "cpu": "Apple M4 Max",
        "gpu": "Apple M4 Max 40-core",
        "memory": "128 GiB",
        "shell": "zsh",
        "terminal": "Terminal.app",
        "de": "Aqua",
        "wm": "Quartz",
        "compositor": "Quartz",
        "resolution": "3456x2234",
        "package_count": "n/a",
        "logo": "macos",
    },
    "server": {
        "os": "Ubuntu Server 24.04 LTS",
        "distro": "Ubuntu 24.04.1 LTS",
        "kernel": "6.8.0-48-generic",
        "architecture": "x86_64",
        "cpu": "AMD EPYC 9654 96-Core",
        "gpu": "None",
        "memory": "2 TiB",
        "shell": "bash",
        "terminal": "bash",
        "de": "headless",
        "wm": "None",
        "compositor": "None",
        "resolution": "Headless",
        "package_count": "1903",
        "logo": "ubuntu",
    },
    "retro": {
        "os": "Windows 98 SE",
        "kernel": "4.10.2222",
        "architecture": "i686",
        "cpu": "Intel Pentium III 733MHz",
        "gpu": "3dfx Voodoo3 3000",
        "memory": "256 MiB",
        "shell": "COMMAND.COM",
        "terminal": "MS-DOS",
        "de": "Classic Theme",
        "wm": "Program Manager",
        "compositor": "None",
        "resolution": "640x480",
        "package_count": "12",
        "package_manager": "Manual",
        "logo": "windows95",
    },
    "gamer": {
        "os": "Windows 11 Pro",
        "kernel": "10.0.22631",
        "architecture": "x86_64",
        "cpu": "AMD Ryzen 9 9950X3D",
        "gpu": "NVIDIA RTX 5090",
        "memory": "64 GiB",
        "shell": "powershell.exe",
        "terminal": "Windows Terminal",
        "de": "Desktop Window Manager",
        "wm": "DWM",
        "compositor": "DWM",
        "resolution": "3840x2160 @ 240Hz",
        "package_count": "too many",
        "package_manager": "winget",
        "logo": "windows",
    },
    "minimal": {
        "os": "Alpine Linux",
        "distro": "Alpine Linux v3.20",
        "kernel": "6.6.41-0-virt",
        "architecture": "x86_64",
        "cpu": "Virtual CPU",
        "memory": "512 MiB",
        "shell": "ash",
        "terminal": "ash",
        "resolution": "80x24",
        "package_count": "47",
        "logo": "alpine",
    },
    "templeos": {
        "os": "TempleOS",
        "distro": "TempleOS v1.0",
        "kernel": "HolyC",
        "architecture": "amd64",
        "cpu": "AMD64 single-core",
        "gpu": "640x480 16-color",
        "memory": "1 GiB",
        "shell": "HolyC",
        "terminal": "HolyC",
        "de": "Single Ring, 640x480 16 color",
        "wm": "God",
        "compositor": "God",
        "resolution": "640x480 16-color",
        "package_count": "0",
        "logo": "templeos",
    },
    "haiku": {
        "os": "Haiku",
        "distro": "Haiku R1/beta4",
        "kernel": "14:58",
        "architecture": "x86_64",
        "cpu": "Intel Core i5-12400",
        "gpu": "Intel UHD Graphics 730",
        "memory": "16 GiB",
        "shell": "bash",
        "terminal": "Terminal",
        "de": "Haiku Desktop",
        "wm": "Decor",
        "compositor": "Compositing",
        "resolution": "1920x1080",
        "package_count": "~900",
        "logo": "haiku",
    },
    "steamdeck": {
        "os": "SteamOS 3.6",
        "distro": "SteamOS",
        "kernel": "6.5.0-valve9-1-neptune",
        "architecture": "x86_64",
        "cpu": "AMD Custom Zen 2",
        "gpu": "AMD RDNA 2 (Steam Deck GPU)",
        "memory": "16 GiB",
        "shell": "bash",
        "terminal": "Konsole",
        "de": "Plasma (Game Mode)",
        "wm": "gamescope",
        "compositor": "gamescope",
        "resolution": "1280x800 @ 60Hz",
        "package_count": "n/a",
        "logo": "steamdeck",
    },
    "ghostbsd": {
        "os": "GhostBSD 24.04",
        "distro": "GhostBSD",
        "kernel": "FreeBSD 14.0-RELEASE",
        "architecture": "amd64",
        "cpu": "Intel Core i7-13700",
        "gpu": "Intel UHD Graphics 770",
        "memory": "32 GiB",
        "shell": "csh",
        "terminal": "xterm",
        "de": "MATE",
        "wm": "Openbox",
        "compositor": "Compton",
        "resolution": "2560x1440",
        "package_count": "2400",
        "package_manager": "pkg",
        "logo": "ghostbsd",
    },
    "android": {
        "os": "Android 14",
        "distro": "LineageOS 21",
        "kernel": "5.15.110-android13",
        "architecture": "aarch64",
        "cpu": "Snapdragon 8 Gen 3",
        "gpu": "Adreno 750",
        "memory": "12 GiB",
        "shell": "sh",
        "terminal": "Termux",
        "de": "Material You",
        "wm": "SurfaceFlinger",
        "compositor": "SurfaceFlinger",
        "resolution": "1080x2400 @ 120Hz",
        "package_count": "n/a",
        "logo": "android",
    },
}


def get_builtin_profiles() -> dict[str, dict[str, str]]:
    """Return built-in profiles as string dicts."""
    return {k: {sk: str(sv) for sk, sv in v.items()} for k, v in BUILTIN_PROFILES.items()}


def get_builtin_profile_names() -> list[str]:
    """Return sorted list of built-in profile names."""
    return sorted(BUILTIN_PROFILES.keys())
